### PR TITLE
add 7 days week to calview, determine automatically if 5 or 7 days ne…

### PR DESCRIPTION
**Pull request by nedimAT**
Hey @dribnif,
i like to work on weekends :) and would like to add the possiblity to view it in the calview.

:v:

### CODE REVIEW

**Comment by dribnif** [comment]
Wohoo! Sounds sweet! I'll give it a once-over asap and do my best to get it merge within the course of this week.

Also sorry for the shitty calview layout code, which you had to deal with. 
I'm still looking for a neat solution here, so if you have any ideas, feel free to jump in.

**Comment by nedimAT** [comment]
thanks, i found everything i needed :)
I'm still a new user. If something jumps to my mind i will share it.

**Comment by dribnif** [comment]
Thanks again for the feature. I had a look at your changes and they seem fine. Found a small issue, with a trailing space in the delimiter of the 5 day week, I'll remove that in the main repo straight. 
I'll release a new version, then I'll close the PR.
Cheerios!

**Comment by dribnif** [comment]
Version 1.0.4 released here https://pypi.org/project/tt-time-tracker/#history, can be updated by running: 

    pip3 install tt-time-tracker --upgrade

Closing PR. 

@nedimAT your contribution is much appreciated :+1:

**Comment by nedimAT** [comment]
cool, it's a pleasure :relaxed:

**Pull request merged**
